 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemmanagement;


import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author test
 */
public class addNewStd extends javax.swing.JFrame {

    static setVisible setVisible;

    /**
     * Creates new form temp_adminHome
     */
    public addNewStd() {
        initComponents();
         setLocation(310,160);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        allStudentResult = new javax.swing.JButton();
        registeredStudent = new javax.swing.JButton();
        addStdResult = new javax.swing.JButton();
        addNewStd = new javax.swing.JButton();
        lebal1 = new javax.swing.JLabel();
        dept = new javax.swing.JLabel();
        lebal2 = new javax.swing.JLabel();
        lebal4 = new javax.swing.JLabel();
        lebal5 = new javax.swing.JLabel();
        lebal6 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        name = new javax.swing.JTextField();
        rollNo = new javax.swing.JTextField();
        branch = new javax.swing.JComboBox<>();
        F_name = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setSize(new java.awt.Dimension(40, 10));

        panel1.setBackground(new java.awt.Color(219, 253, 218));

        jLabel1.setFont(new java.awt.Font("K2D", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Portal");

        back.setBackground(new java.awt.Color(102, 102, 255));
        back.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        allStudentResult.setBackground(new java.awt.Color(0, 51, 51));
        allStudentResult.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        allStudentResult.setForeground(java.awt.SystemColor.textHighlight);
        allStudentResult.setText("All Student Result");
        allStudentResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        allStudentResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudentResultActionPerformed(evt);
            }
        });

        registeredStudent.setBackground(new java.awt.Color(0, 51, 51));
        registeredStudent.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        registeredStudent.setForeground(java.awt.SystemColor.textHighlight);
        registeredStudent.setText("Registered Student");
        registeredStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registeredStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredStudentActionPerformed(evt);
            }
        });

        addStdResult.setBackground(new java.awt.Color(0, 51, 51));
        addStdResult.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addStdResult.setForeground(java.awt.SystemColor.textHighlight);
        addStdResult.setText("Add Student Result");
        addStdResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addStdResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStdResultActionPerformed(evt);
            }
        });

        addNewStd.setBackground(new java.awt.Color(153, 255, 204));
        addNewStd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addNewStd.setForeground(new java.awt.Color(0, 102, 102));
        addNewStd.setText("Add New Student");
        addNewStd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addNewStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(allStudentResult, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registeredStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addStdResult, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewStd, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(addNewStd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(addStdResult, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(registeredStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(allStudentResult, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        lebal1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lebal1.setForeground(new java.awt.Color(0, 102, 102));
        lebal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lebal1.setText("Name : ");
        lebal1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lebal1.setSize(new java.awt.Dimension(40, 10));

        dept.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        dept.setForeground(new java.awt.Color(0, 102, 102));
        dept.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dept.setText("Department :");
        dept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dept.setSize(new java.awt.Dimension(40, 10));

        lebal2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lebal2.setForeground(new java.awt.Color(0, 102, 102));
        lebal2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lebal2.setText("Roll Number :");
        lebal2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lebal2.setSize(new java.awt.Dimension(40, 10));

        lebal4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lebal4.setForeground(new java.awt.Color(0, 102, 102));
        lebal4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lebal4.setText("Course :");
        lebal4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lebal4.setSize(new java.awt.Dimension(40, 10));

        lebal5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lebal5.setForeground(new java.awt.Color(0, 102, 102));
        lebal5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lebal5.setText("Gender :");
        lebal5.setSize(new java.awt.Dimension(40, 10));

        lebal6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lebal6.setForeground(new java.awt.Color(0, 102, 102));
        lebal6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lebal6.setText("Father Name :");
        lebal6.setSize(new java.awt.Dimension(40, 10));

        department.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        department.setForeground(new java.awt.Color(0, 51, 102));
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Department", "B.Tech", "M.Tech", "B.Sc", "M.Sc", "BBA", "MBA", "B.Com", "M.Com", "B.A", "M.A", " ", " " }));

        branch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        branch.setForeground(new java.awt.Color(0, 51, 102));
        branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Course", "Computer Science", "Information Technology", "Civil Engineering", "Electricals Engineering", "Mechanical Engineering", "Electronics Engineering", "Artificial Intelligence", "Machine Learning", "Physics owners", "chemestry owners", "maths owners", "english", "history owners", "sociology owners" }));

        submit.setBackground(new java.awt.Color(0, 102, 102));
        submit.setFont(new java.awt.Font("BM Dohyeon", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Save & Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Gender", "Male", "Female", "Others" }));

        jLabel8.setFont(new java.awt.Font("K2D", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Manage Student Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lebal5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lebal4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dept, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lebal2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lebal1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lebal6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rollNo)
                                .addComponent(department, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(branch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F_name)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(submit)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lebal1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lebal2)
                    .addComponent(rollNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dept)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lebal4)
                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lebal5)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lebal6)
                    .addComponent(F_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
   
            setVisible(false);
            new adminHome().setVisible(true);   
//            adminIndex frame=new adminIndex();
//            frame.setVisible(true);
        

    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:                                       

    String Name = name.getText();
    String Roll = rollNo.getText();
    String Dept = (String) department.getSelectedItem();
    String Branch = (String) branch.getSelectedItem();
    String Gender = (String) gender.getSelectedItem();
    String FatherName = F_name.getText();
    
    try {
        // Load MySQL JDBC driver
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/srms", "root", "rootsystem");
       
        Statement st = con.createStatement();
        st.executeUpdate("insert into student(rollNo, course, branchName, name, gender,fathername) VALUES('"+Roll+"','"+Dept+"','"+Branch+"','"+Name+"','"+Gender+"','"+FatherName+"')");
        // Success message
        JOptionPane.showMessageDialog(null, "Data Saved Successfully");
        setVisible(false);
        new addNewStd().setVisible(true);
        
    } catch (Exception e) {
        // Log error and show message dialog
        JOptionPane.showMessageDialog(null, e.toString());
        Logger.getLogger(addNewStd.class.getName()).log(Level.SEVERE, null, e);
    
} 


    }//GEN-LAST:event_submitActionPerformed

    private void allStudentResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudentResultActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new allStudentResult().setVisible(true);
    }//GEN-LAST:event_allStudentResultActionPerformed

    private void registeredStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new registeredStudent().setVisible(true);
    }//GEN-LAST:event_registeredStudentActionPerformed

    private void addStdResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStdResultActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new addStdResult().setVisible(true);
    }//GEN-LAST:event_addStdResultActionPerformed

    private void addNewStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStdActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_addNewStdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewStd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewStd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewStd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewStd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewStd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField F_name;
    private javax.swing.JButton addNewStd;
    private javax.swing.JButton addStdResult;
    private javax.swing.JButton allStudentResult;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> branch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JLabel dept;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lebal1;
    private javax.swing.JLabel lebal2;
    private javax.swing.JLabel lebal4;
    private javax.swing.JLabel lebal5;
    private javax.swing.JLabel lebal6;
    private javax.swing.JTextField name;
    private java.awt.Panel panel1;
    private javax.swing.JButton registeredStudent;
    private javax.swing.JTextField rollNo;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
